image: centos:7
build:
    script:
        - run curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ./install_rustup.sh
        - run echo '' | bash ./install_rustup.sh -y
        - env PATH "/root/.cargo/bin:${PATH}"
        - cargo build --release
    artifacts:
        paths:
            - target/release/git-poly
        expire_in: 1 week
