stages:
    - build
    - deploy

build_linux:
    stage: build
    image: rust:1.40-alpine
    script:
        - yum install -y gcc
        - yum install -y curl
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ./install_rustup.sh
        - echo '' | bash ./install_rustup.sh -y
        - export PATH="/root/.cargo/bin:${PATH}"
        - rustup target add x86_64-unknown-linux-musl
        - cargo build --release --target x86_64-unknown-linux-musl
        - uname -r
    artifacts:
        paths:
            - target/x86_64-unknown-linux-musl/release/git-p
        expire_in: 1 week

build_docs:
    stage: build
    image: rust:1.40-alpine
    script:
        - bash build_doc.sh
    artifacts:
        paths:
            - doc
        expire_in: 1 week

pages:
    stage: pages
    image: centos:7
    script:
        - mkdir -p public/linux
        - cp doc/* public/
        - cp target/x85_64-unknown-linux-musl/release/git-p public/linux/

    artifacts:
        paths:
            - public
