stages:
    - build
    - deploy

build_linux:
    stage: build
    image: rust:1.40-alpine
    script:
        - rustup target add x86_64-unknown-linux-musl
        - cargo build --release --target x86_64-unknown-linux-musl
        - uname -r
        - uname -r > target/kernel_version.txt
    artifacts:
        paths:
            - target/x86_64-unknown-linux-musl/release/git-p
        expire_in: 1 week

build_docs:
    stage: build
    image: rust:1.40-alpine
    script:
        - rustdoc getting_started.md --markdown-css milligram.min.css
    artifacts:
        paths:
            - doc
        expire_in: 1 week

pages:
    only:
        - master
    stage: deploy
    image: centos:7
    script:
        - mkdir -p public/linux
        - cp doc/* public/
        - cp target/x85_64-unknown-linux-musl/release/git-p public/linux/

    artifacts:
        paths:
            - public
