stages:
    - doc
    - build
    - deploy

build_linux:
    stage: build
    image: rust:1.40-alpine
    script:
        - mkdir -p .cargo
        - rustup target add x86_64-unknown-linux-musl
        - env CARGO_HOME=$PWD/.cargo cargo build --release --target x86_64-unknown-linux-musl
        - uname -r
        - uname -r > target/kernel_version.txt
    artifacts:
        paths:
            - target
        expire_in: 1 week
    cache:
        paths:
            - .cargo

build_docs:
    stage: doc
    image: rust:1.40-alpine
    script:
        - rustdoc getting_started.md --markdown-css milligram.min.css
    artifacts:
        paths:
            - doc
        expire_in: 1 week

pages:
    #only:
    #    - master
    stage: deploy
    image: centos:7
    script:
        - mkdir -p public/linux
        - cp doc/* public/
        - cp target/x85_64-unknown-linux-musl/release/git-p public/linux/
    dependencies:
        - build_docs
        - build_linux
    artifacts:
        paths:
            - public
